// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// fastdcor
double fastdcor(arma::vec x, arma::vec y);
RcppExport SEXP _SIStree_fastdcor(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(fastdcor(x, y));
    return rcpp_result_gen;
END_RCPP
}
// gini_split
List gini_split(arma::mat X, arma::vec y, int minleaf, int numLabels);
RcppExport SEXP _SIStree_gini_split(SEXP XSEXP, SEXP ySEXP, SEXP minleafSEXP, SEXP numLabelsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type minleaf(minleafSEXP);
    Rcpp::traits::input_parameter< int >::type numLabels(numLabelsSEXP);
    rcpp_result_gen = Rcpp::wrap(gini_split(X, y, minleaf, numLabels));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_SIStree_fastdcor", (DL_FUNC) &_SIStree_fastdcor, 2},
    {"_SIStree_gini_split", (DL_FUNC) &_SIStree_gini_split, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_SIStree(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
