# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fastdcor <- function(x, y) {
    .Call(`_SIStree_fastdcor`, x, y)
}

gini_split <- function(X, y, minleaf, numLabels) {
    .Call(`_SIStree_gini_split`, X, y, minleaf, numLabels)
}

